services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./dist:/app/react-app/dist
    environment:
      - NODE_ENV=production
