# Generated by Django 5.0.1 on 2024-01-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="delete flag"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                ("password", models.CharField(max_length=20, verbose_name="password")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "user",
                "db_table": "user",
            },
        ),
    ]
