# Generated by Django 5.0.1 on 2024-01-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="avatar"
            ),
        ),
    ]
