# Generated by Django 5.0.1 on 2024-01-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="bio"
            ),
        ),
    ]
