# Generated by Django 5.0.1 on 2024-01-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_user_date_joined_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100, verbose_name="password"),
        ),
    ]
